### PR TITLE
Add npm files filter

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by defunctzombie** [comment]
please reword the commit to `package.json: add 'files' field`

Your current commit message is not too clear. (same with your PR to any of my other repos plz).

**Comment by TrySound** [comment]
@defunctzombie  Done

**Comment by defunctzombie** [comment]
I think something nice for other PRs might be to also include the LICENSE file since that one is pretty important.

**Comment by TrySound** [comment]
@defunctzombie https://github.com/defunctzombie/node-url/pull/20
> LICENSE and README.md won't be ignored.

**Comment by defunctzombie** [comment]
@TrySound is that an npm feature to never ignore the license and readme files?

**Comment by TrySound** [comment]
@defunctzombie Yeah https://docs.npmjs.com/files/package.json#files
>Certain files are always included, regardless of settings:
  package.json
  README (and its variants)
  CHANGELOG (and its variants)
  LICENSE / LICENCE

**Comment by defunctzombie** [comment]
:+1:

**Pull request merged**
