### PR TITLE
process doesn't exist outside Node

### PR DESCRIPTION
**Pull request by ComLock**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
It doesn't need to - this is a node module, and all non-broken node module bundlers polyfill `process` automatically.

**Comment by ComLock** [comment]
I'm using tsup, with esbuild and swc(for commonjs).

**Comment by ljharb** [comment]
If esbuild doesn't polyfill `process` by default, then it's broken - presumably you can configure it to do that, though.

**Comment by ComLock** [comment]
I'll try this one (tomorrow) https://github.com/cyco130/esbuild-plugin-polyfill-node

**Pull request closed without merging**
