### PR TITLE
fix issue #11

### PR DESCRIPTION
**Pull request by bernardmcmanus**

### CODE REVIEW

**Comment by Hypercubed** [comment]
This is pretty on... but I'm hitting this issue now.

**Comment by bernardmcmanus** [comment]
@Hypercubed OOC, do you know if this happens with webpack?

**Comment by bernardmcmanus** [comment]
@goto-bus-stop updated

**Comment by Hypercubed** [comment]
@bernardmcmanus I'm seeing it in an Angular app, which is using webpack.  But I'mn not loading `util` directly... it's a dep of a dep.

**Comment by goto-bus-stop** [comment]
:package: 0.11.1

**Pull request merged**
